[package]
name = "termlib-server"
version = "0.2.0"
edition = "2021"

[dependencies]
comrak = { version = "0.28.0", features = ["syntect", "emojis"], default-features = false }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "io-std"] }
log = "0.4.22"
url = "2.5.2"
rocket = { version = "0.5.1", features = ["json"] }
fern = { version = "0.6.2", features = ["chrono", "colored"] }
chrono = "0.4.38"
tempfile = "3.12.0"
reqwest = { version = "0.12.15", default-features = false, features = ["http2", "json", "rustls-tls"] }
serde = { version = "1.0.219", default-features = false }
serde_json = { version = "1.0.140", default-features = false }
octocrab = { version = "0.44.0", default-features = false, features = ["default-client", "rustls"] }
tera = { version = "1.20.0", default-features = false }
liquid = "0.26.11"
liquid-core = { version = "0.26.11", features = ["derive"] }
shell-quote = { version = "0.7.2", default-features = false, features = ["bash", "sh"] }
anyhow = "1.0.98"
