[package]
name = "termlib-server"
version = "0.3.0"
edition = "2021"

[dependencies]
comrak = { version = "0.28.0", features = ["syntect", "emojis"], default-features = false }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "io-std"] }
url = "2.5.2"
rocket = { version = "0.5.1", features = ["json"] }
fern = { version = "0.6.2", features = ["chrono", "colored"] }
chrono = "0.4.38"
serde_json = { version = "1.0.140", default-features = false }
octocrab = { version = "0.44.0", features = ["default-client", "hyper-rustls", "rustls", "rustls-ring"], default-features = false }
tera = { version = "1.20.0", default-features = false, features = ["builtins"] }
shell-quote = { version = "0.7.2", default-features = false, features = ["bash", "sh"] }
anyhow = "1.0.98"
rocket_okapi = { version = "0.9.0", features = ["rapidoc"] }
schemars = "0.8.22"
mime = "0.3.17"
log = "0.4.27"
