name: Lint + Test

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
      - name: format
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- -D warnings


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
      - name: test
        run: cargo test
