name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CLONE_DIR: server

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{env.CLONE_DIR}}
      - run: echo "SHORTREF=$(git -C ${{CLONE_DIR}} rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: google-github-actions/auth@v2
        with:
          project_id: termlibs
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
          export_environment_variables: true
      - run: gcloud auth configure-docker gcr.io
      - uses: google-github-actions/setup-gcloud@v2
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{env.CLONE_DIR}}
          file: server/Dockerfile
          push: true
          tags: gcr.io/termlibs/images/server:${{env.SHORTREF}}
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: server
          image: gcr.io/termlibs/images/server:${{env.SHORTREF}}
